# Generated by Django 5.2.6 on 2025-11-01 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(help_text='Token de API de Deriv', max_length=255)),
                ('app_id', models.CharField(default='1089', help_text='App ID de Deriv', max_length=50)),
                ('is_demo', models.BooleanField(default=True, help_text='¿Usar cuenta demo?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deriv_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración API Deriv',
                'verbose_name_plural': 'Configuraciones API Deriv',
            },
        ),
        migrations.CreateModel(
            name='TradingBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(default='R_100', help_text='Símbolo a operar (ej: R_100, EURUSD)', max_length=50)),
                ('contract_type', models.CharField(default='CALL', help_text='Tipo de contrato', max_length=50)),
                ('duration', models.IntegerField(default=1, help_text='Duración en minutos')),
                ('duration_unit', models.CharField(default='m', help_text='Unidad de duración (s, m, h)', max_length=10)),
                ('max_daily_loss', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('max_daily_trades', models.IntegerField(default=100)),
                ('daily_profit_target', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('stopped', 'Detenido'), ('running', 'Ejecutando'), ('paused', 'Pausado'), ('error', 'Error')], default='stopped', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('today_trades', models.IntegerField(default=0)),
                ('today_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('today_wins', models.IntegerField(default=0)),
                ('today_losses', models.IntegerField(default=0)),
                ('last_trade_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot de Trading',
                'verbose_name_plural': 'Bots de Trading',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('symbol', models.CharField(max_length=50)),
                ('contract_type', models.CharField(max_length=50)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration', models.IntegerField()),
                ('duration_unit', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('open', 'Abierta'), ('won', 'Ganada'), ('lost', 'Perdida'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading_bot.tradingbot')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Advertencia'), ('error', 'Error'), ('success', 'Éxito')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trading_bot.tradingbot')),
            ],
            options={
                'verbose_name': 'Log del Bot',
                'verbose_name_plural': 'Logs de Bots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strategy_type', models.CharField(choices=[('martingale', 'Martingala'), ('fibonacci', 'Fibonacci'), ('fixed', 'Monto Fijo'), ('percentage', 'Porcentaje del Balance'), ('trend_following', 'Seguimiento de Tendencia'), ('mean_reversion', 'Reversión a la Media'), ('breakout', 'Ruptura de Niveles'), ('custom', 'Personalizada')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('initial_stake', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('max_stake', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('config', models.JSONField(default=dict, help_text='Configuración específica de la estrategia')),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estrategia de Trading',
                'verbose_name_plural': 'Estrategias de Trading',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tradingbot',
            name='strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading_bot.tradingstrategy'),
        ),
    ]
