# Generated by Django 5.2.6 on 2025-11-02 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0002_add_scope_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='derivapiconfig',
            name='scope_admin',
        ),
        migrations.RemoveField(
            model_name='derivapiconfig',
            name='scope_operate',
        ),
        migrations.RemoveField(
            model_name='derivapiconfig',
            name='scope_payments',
        ),
        migrations.RemoveField(
            model_name='derivapiconfig',
            name='scope_read',
        ),
        migrations.RemoveField(
            model_name='derivapiconfig',
            name='scope_trading_information',
        ),
    ]
