# Generated by Django 5.2.7 on 2025-10-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('timeframe', models.CharField(choices=[('1m', '1m'), ('5m', '5m'), ('15m', '15m'), ('1h', '1h'), ('1d', '1d'), ('1w', '1w')], db_index=True, max_length=8)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'timeframe', 'timestamp'], name='market_cand_symbol_085c22_idx')],
                'unique_together': {('symbol', 'timeframe', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('zone_period', models.CharField(choices=[('DAY', 'DAY'), ('WEEK', 'WEEK')], db_index=True, max_length=8)),
                ('zone_low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('zone_high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Periodo al que corresponde la zona')),
                ('zone_height', models.DecimalField(decimal_places=8, max_digits=20)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'zone_period', 'timestamp'], name='market_zone_symbol_cb98d6_idx')],
            },
        ),
    ]
