# Generated by Django 5.2.7 on 2025-10-15 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquiditySweep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('sweep_time', models.DateTimeField(db_index=True)),
                ('direction', models.CharField(choices=[('long', 'long'), ('short', 'short')], max_length=8)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sweeps', to='market.zone')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'sweep_time'], name='market_liqu_symbol_095b2b_idx')],
            },
        ),
    ]
