# Generated by Django 5.2.7 on 2025-10-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_liquiditysweep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='market_tick_symbol_013870_idx')],
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
    ]
