"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Variables de entorno (configurar manualmente o usar .env)
# DERIV_API_TOKEN=rOB3RNqw1EevPzu


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)(k7erfpc)g&lhbs29)-0*-&#4di^&)5j9&b%*rxb4+px3x#s8'

# SECURITY WARNING: don't run with debug turned on in production!
# Usar variable de entorno DJANGO_DEBUG ("1"/"0"). Default: False en servidor
DEBUG = os.getenv('DJANGO_DEBUG', '0') == '1'

# ALLOWED HOSTS - Configuración para producción
# En desarrollo: permitir todo
# En producción: solo dominios específicos
ALLOWED_HOSTS = os.getenv(
    'DJANGO_ALLOWED_HOSTS',
    'localhost,127.0.0.1,vitalmix.com.co,www.vitalmix.com.co'
).split(',')

# CSRF trusted origins para despliegue detrás de Nginx/HTTPS
CSRF_TRUSTED_ORIGINS = os.getenv(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    'https://vitalmix.com.co,https://www.vitalmix.com.co'
).split(',')

# Dominio de producción
PRODUCTION_DOMAIN = 'www.vitalmix.com.co'
PRODUCTION_IP = '92.113.39.100'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # DRF
    'rest_framework',
    # Apps del proyecto
    'market',
    'engine',
    'trader',
    'learning',
    'connectors',
    'monitoring',
    'trading_bot',
]

# Agregar apps de Celery solo si están instaladas
try:
    import django_celery_beat
    INSTALLED_APPS.append('django_celery_beat')
except ImportError:
    pass

try:
    import django_celery_results
    INSTALLED_APPS.append('django_celery_results')
except ImportError:
    pass

# Channels para WebSocket
try:
    import channels
    INSTALLED_APPS.append('channels')
    ASGI_APPLICATION = 'config.asgi.application'
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
except ImportError:
    pass

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.getenv('POSTGRES_HOST'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'intradia'),
            'USER': os.getenv('POSTGRES_USER', 'intradia'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'intradia'),
            'HOST': os.getenv('POSTGRES_HOST', 'db'),
            'PORT': int(os.getenv('POSTGRES_PORT', '5432')),
            'OPTIONS': {
                'client_encoding': 'UTF8',
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 30,  # Timeout de 30 segundos para esperar que se libere el lock
                'check_same_thread': False,  # Permitir acceso desde múltiples threads
            },
        }
    }
    
    # Configurar WAL mode para SQLite (permite lecturas concurrentes mientras se escribe)
    # Esto se hace después de la conexión inicial
    import sqlite3
    try:
        conn = sqlite3.connect(str(BASE_DIR / 'db.sqlite3'))
        conn.execute('PRAGMA journal_mode=WAL;')
        conn.execute('PRAGMA busy_timeout=30000;')  # 30 segundos en milisegundos
        conn.execute('PRAGMA synchronous=NORMAL;')  # Balance entre seguridad y rendimiento
        conn.close()
    except Exception as e:
        print(f'⚠️ No se pudo configurar WAL mode: {e}')


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Carpeta donde collectstatic recopila archivos en producción
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Login URLs
LOGIN_URL = 'cuentas:login'
LOGIN_REDIRECT_URL = 'engine:dashboard'
LOGOUT_REDIRECT_URL = 'cuentas:login'

# Session Configuration - Reducir bloqueos de BD
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'  # Cache + BD para mejor rendimiento
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 86400  # 24 horas
SESSION_SAVE_EVERY_REQUEST = False  # No guardar en cada request para reducir accesos a BD

# Cache Configuration - Para sesiones y mejor rendimiento
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# Celery / Redis
REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
# Celery Configuration - Para desarrollo usar base de datos (sin Redis)
# Usar 'memory' como broker temporal si no hay Redis instalado
# Usar 'memory://' que funciona en el mismo proceso
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'memory://')
CELERY_RESULT_BACKEND = 'cache+memory://'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_CACHE_BACKEND = 'django-cache'

TIME_ZONE = os.getenv('TIMEZONE', TIME_ZONE)

# Celery Beat schedule (ejemplos, ajustar símbolos vía env)
SYMBOLS = os.getenv('SYMBOLS', 'EURUSD,GBPUSD,USDJPY').split(',')

# Importar celery solo si está disponible
try:
    from celery.schedules import crontab
    CELERY_BEAT_SCHEDULE = {
        # Refrescar zonas diarias a las 00:05 UTC
        'refresh-daily-zones': {
            'task': 'engine.tasks.refresh_daily_weekly_zones',
            'schedule': crontab(minute=5, hour=0),
            'args': (SYMBOLS[0],),
        },
        # Escaneo intradía cada 5 minutos
        'scan-intraday-sweeps': {
            'task': 'engine.tasks.scan_intraday_sweeps',
            'schedule': 300.0,
            'args': (SYMBOLS[0], 1, '5m'),  # zone_id dummy, será inyectado desde runtime
        },
        # TRADING AUTOMÁTICO - Procesar TODOS los instrumentos activos cada 2 segundos
        'auto-trading-all-symbols': {
            'task': 'engine.tasks.process_all_active_symbols',
            'schedule': 2.0,  # Cada 2 segundos para no sobrecargar
            'args': (),
        },
        # Obtener datos frescos cada hora
        'fetch-fresh-data': {
            'task': 'engine.tasks.fetch_historical_data',
            'schedule': 3600.0,  # cada hora
            'args': (SYMBOLS[0], '5m', 100),
        },
}
except ImportError:
    # Celery no está instalado, usar configuración vacía
    CELERY_BEAT_SCHEDULE = {}

# Deriv API Configuration
DERIV_API_TOKEN = os.getenv('DERIV_API_TOKEN', 'rOB3RNqw1EevPzu')
DERIV_ACCOUNT_ID = os.getenv('DERIV_ACCOUNT_ID', '')

# Channels ya configurado arriba en el try/except
