# Generated by Django 5.2.7 on 2025-10-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('rule', 'rule'), ('rl', 'rl')], default='rule', max_length=8)),
                ('shadow_enabled', models.BooleanField(default=True)),
                ('last_promoted_at', models.DateTimeField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
