# Generated by Django 5.2.7 on 2025-10-15 20:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('request_payload', models.JSONField()),
                ('response_payload', models.JSONField()),
                ('request_hash', models.CharField(db_index=True, max_length=64)),
                ('accepted', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
