# Generated by Django 5.2.7 on 2025-10-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaudit',
            name='action',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='orderaudit',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderaudit',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='orderaudit',
            name='latency_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderaudit',
            name='pnl',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='orderaudit',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='orderaudit',
            name='response_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='orderaudit',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='orderaudit',
            name='status',
            field=models.CharField(db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='orderaudit',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='orderaudit',
            name='symbol',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='orderaudit',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderaudit',
            name='request_payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='orderaudit',
            name='response_payload',
            field=models.JSONField(default=dict),
        ),
    ]
