# Generated by Django 5.2.6 on 2025-11-01 02:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_target', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Meta de ganancia diaria en USD', max_digits=10)),
                ('max_loss', models.DecimalField(decimal_places=2, default=Decimal('-50.00'), help_text='Pérdida máxima diaria en USD', max_digits=10)),
                ('max_trades', models.IntegerField(default=50, help_text='Máximo número de trades por día')),
                ('profit_target_pct', models.FloatField(default=2.0, help_text='Meta de ganancia diaria como porcentaje del balance inicial')),
                ('max_loss_pct', models.FloatField(default=1.0, help_text='Pérdida máxima diaria como porcentaje del balance inicial')),
                ('protect_profits', models.BooleanField(default=True, help_text='Activar protección de ganancias')),
                ('profit_protection_pct', models.FloatField(default=0.5, help_text='Porcentaje de ganancia a proteger (0.5 = 50%)')),
                ('is_active', models.BooleanField(default=True, help_text='Configuración activa')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuración de Capital',
                'verbose_name_plural': 'Configuraciones de Capital',
                'ordering': ['-updated_at'],
            },
        ),
    ]
