# Generated by Django 5.2.6 on 2025-11-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalconfig',
            name='anti_martingale_multiplier',
            field=models.FloatField(default=1.5, help_text='Multiplicador después de ganancia (Anti-Martingala)'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='anti_martingale_reset_on_loss',
            field=models.BooleanField(default=True, help_text='Resetear a tamaño base después de pérdida'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='atr_multiplier',
            field=models.FloatField(default=2.0, help_text='Multiplicador del ATR para stop loss'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='kelly_fraction',
            field=models.FloatField(default=0.25, help_text='Fracción del Kelly óptimo a usar (0.25 = 25%, más conservador)'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='max_concurrent_positions',
            field=models.IntegerField(default=5, help_text='Máximo de posiciones simultáneas'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='max_drawdown_pct',
            field=models.FloatField(default=10.0, help_text='Drawdown máximo permitido (%)'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='max_risk_per_trade_pct',
            field=models.FloatField(default=2.0, help_text='Máximo riesgo por trade como % del capital'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='position_sizing_method',
            field=models.CharField(choices=[('kelly', 'Kelly Criterion (Óptimo)'), ('kelly_fractional', 'Kelly Fractional (Conservador)'), ('fixed_fractional', 'Fixed Fractional (Porcentaje Fijo)'), ('anti_martingale', 'Anti-Martingala (Aumentar tras ganancias)'), ('volatility', 'Volatility-Based (Basado en ATR)'), ('risk_parity', 'Risk Parity (Riesgo Equitativo)')], default='kelly_fractional', help_text='Método de cálculo de tamaño de posición', max_length=20),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='reduce_size_on_drawdown',
            field=models.BooleanField(default=True, help_text='Reducir tamaño de posición durante drawdown'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='risk_per_trade_pct',
            field=models.FloatField(default=1.0, help_text='Porcentaje del capital a arriesgar por trade (Fixed Fractional)'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='target_volatility',
            field=models.FloatField(default=15.0, help_text='Volatilidad objetivo para Risk Parity (%)'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='var_confidence',
            field=models.FloatField(default=0.95, help_text='Nivel de confianza para VaR (0.95 = 95%)'),
        ),
    ]
