# Generated by Django 5.2.6 on 2025-11-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_capitalconfig_anti_martingale_multiplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalconfig',
            name='close_losing_positions_after_minutes',
            field=models.IntegerField(default=30, help_text='Cerrar posiciones perdedoras después de X minutos'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='emergency_drawdown_threshold_pct',
            field=models.FloatField(default=5.0, help_text='Drawdown máximo en 5 min para activar emergencia (%)'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='enable_emergency_stop',
            field=models.BooleanField(default=True, help_text='Detener trading en caídas súbitas'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='enable_time_based_stops',
            field=models.BooleanField(default=True, help_text='Cerrar posiciones estancadas automáticamente'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='enable_trailing_stop',
            field=models.BooleanField(default=True, help_text='Protección automática de ganancias (trailing stop)'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='enable_volatility_scaling',
            field=models.BooleanField(default=True, help_text='Ajustar tamaño según volatilidad'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='high_volatility_threshold',
            field=models.FloatField(default=2.0, help_text='Umbral de alta volatilidad (múltiplo del promedio)'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='max_active_positions',
            field=models.IntegerField(default=10, help_text='Máximo número de posiciones simultáneas'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='max_correlated_exposure_pct',
            field=models.FloatField(default=10.0, help_text='Máxima exposición a símbolos correlacionados (%)'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='max_portfolio_risk_pct',
            field=models.FloatField(default=15.0, help_text='Máximo riesgo total del portafolio (%)'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='max_position_duration_minutes',
            field=models.IntegerField(default=60, help_text='Cerrar posición si no gana después de X minutos'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='max_single_position_risk_pct',
            field=models.FloatField(default=5.0, help_text='Máximo riesgo por posición individual (%)'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='min_profit_for_trailing_pct',
            field=models.FloatField(default=0.5, help_text='Ganancia mínima para activar trailing stop (%)'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='trailing_stop_distance_pct',
            field=models.FloatField(default=1.0, help_text='Distancia del trailing stop (%)'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='volatility_reduction_pct',
            field=models.FloatField(default=50.0, help_text='Reducción de tamaño en alta volatilidad (%)'),
        ),
    ]
