# Generated by Django 5.2.6 on 2025-11-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_capitalconfig_close_losing_positions_after_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalconfig',
            name='default_duration_forex',
            field=models.IntegerField(default=900, help_text='Duración por defecto para forex (segundos)'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='default_duration_indices',
            field=models.IntegerField(default=30, help_text='Duración por defecto para índices (segundos)'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='default_duration_metals',
            field=models.IntegerField(default=300, help_text='Duración por defecto para metales (segundos)'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='max_amount_absolute',
            field=models.FloatField(default=500.0, help_text='Límite absoluto máximo de amount'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='max_amount_pct_balance',
            field=models.FloatField(default=5.0, help_text='Máximo amount como % del balance (5% = muy conservador)'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='min_amount_per_trade',
            field=models.FloatField(default=1.0, help_text='Amount mínimo permitido por trade'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='min_trade_interval_seconds',
            field=models.IntegerField(default=60, help_text='Tiempo mínimo entre trades del mismo símbolo (segundos)'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='symbol_amount_limits',
            field=models.JSONField(blank=True, default=dict, help_text="Límites de amount máximo por símbolo (ej: {'RDBULL': 100.0, 'RDBEAR': 100.0})"),
        ),
    ]
