# Generated by Django 5.2.6 on 2025-11-01 04:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_capitalconfig_default_duration_forex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalconfig',
            name='disable_max_trades',
            field=models.BooleanField(default=False, help_text='Desactivar límite de trades (útil para pruebas)'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='disable_profit_target',
            field=models.BooleanField(default=False, help_text='Desactivar meta de ganancia (útil para pruebas)'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='stop_loss_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de pérdida para cerrar trading (0 = desactivado)', max_digits=10),
        ),
    ]
