# Generated by Django 5.2.6 on 2025-11-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_capitalconfig_disable_max_trades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalconfig',
            name='emergency_drawdown_threshold_pct',
            field=models.FloatField(default=10.0, help_text='Drawdown máximo en 5 min para activar emergencia (%)'),
        ),
        migrations.AlterField(
            model_name='capitalconfig',
            name='profit_target_pct',
            field=models.FloatField(default=5.0, help_text='Meta de ganancia diaria como porcentaje del balance inicial'),
        ),
    ]
