# Generated by Django 5.2.6 on 2025-11-03 02:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_update_emergency_drawdown_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalconfig',
            name='enable_martingale',
            field=models.BooleanField(default=False, help_text='Activar sistema de martingala (aumentar monto después de pérdidas)'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='martingale_base_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Monto base para martingala ($0.10)', max_digits=10),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='martingale_max_levels',
            field=models.IntegerField(default=5, help_text='Profundidad máxima de martingala (niveles antes de resetear)'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='martingale_multiplier',
            field=models.FloatField(default=2.0, help_text='Multiplicador de martingala después de pérdida (2.0 = duplicar)'),
        ),
        migrations.AddField(
            model_name='capitalconfig',
            name='martingale_reset_on_win',
            field=models.BooleanField(default=True, help_text='Resetear martingala después de ganancia'),
        ),
    ]
